# Generated by Django 3.1.14 on 2023-11-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prisoner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('f_name', models.CharField(max_length=15, verbose_name='First Name')),
                ('l_name', models.CharField(max_length=15, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=50)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('blood_tp', models.CharField(blank=True, max_length=50, verbose_name='Blood Type')),
                ('offense_type', models.CharField(max_length=50)),
                ('phone_number', models.BigIntegerField()),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('state', models.CharField(max_length=50)),
                ('nationality', models.CharField(default='Nigeria', max_length=50)),
                ('tribe', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='prisoner/images', verbose_name='Passport')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
